const CDN_BASE = import.meta.env.VITE_CDN_BASE;
const imgLocation = `${CDN_BASE}/nonFruitCharacters/`


const characters = [
    { name: "Gol D. Roger", power: 100, tag: "none", img: `${imgLocation}/Gol-D-Roger.webp` },
    { name: "Rocks D. Xebec", power: 100, tag: "none", img: `${imgLocation}/Rocks.webp` },
    { name: "Whitebeard", power: 100, tag: "none", img: `${imgLocation}/Edward-Newgate-Anime-Infobox.webp` },
    { name: "Monkey D. Garp", power: 100, tag: "none", img: `${imgLocation}/Monkey-D-Garp-Anime-Infobox.webp` },
    { name: "Kozuki Oden", power: 95, tag: "swordsman", img: `${imgLocation}/kozuki-oden-20103.webp` },
    { name: "King", power: 89, tag: "none", img: `${imgLocation}/King-at-Age-19.webp` },
    { name: "Queen", power: 84, tag: "scientist", img: `${imgLocation}/queen.webp` },
    { name: "Jack", power: 83, tag: "none", img: `${imgLocation}/Jack-Anime-Infobox.webp` },
    { name: "Ryokugyu", power: 93, tag: "none", img: `${imgLocation}/Aramaki-Anime-Infobox.webp` },
    { name: "Shiryu", power: 85, tag: "swordsman", img: `${imgLocation}/Shiryu-Anime-Infobox.webp` },
    { name: "Cracker", power: 85, tag: "none", img: `${imgLocation}/Charlotte-Cracker-Anime-Infobox.webp` },
    { name: "Vista", power: 87, tag: "swordsman", img: `${imgLocation}/Vista-Anime-Infobox.webp` },
    { name: "Jesus Burgess", power: 80, tag: "none", img: `${imgLocation}/Jesus-Burgess-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Van Augur", power: 79, tag: "sniper", img: `${imgLocation}/Van-Augur-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Perospero", power: 80, tag: "candy", img: `${imgLocation}/Charlotte-Perospero-Anime-Infobox.webp` },
    { name: "Oven", power: 79, tag: "fire", img: `${imgLocation}/Charlotte-Oven-Anime-Infobox.webp` },
    { name: "Brook", power: 76, tag: "musician", img: `${imgLocation}/e3d8d71c26554aa363a8cd12e40065f7.webp` },
    { name: "Nico Robin", power: 80, tag: "none", img: `${imgLocation}/Nico-robin-dressrosa-01.webp` },
    { name: "Bon Clay", power: 75, tag: "none", img: `${imgLocation}/Bentham-Anime-Infobox.webp` },
    { name: "Kaido", power: 98, tag: "giant", img: `${imgLocation}/Kaidou-Anime-Infobox.webp` },
    { name: "Big Mom", power: 97, tag: "giant", img: `${imgLocation}/Charlotte-Linlin-Anime-Infobox.webp` },
    { name: "Shanks", power: 98, tag: "swordsman", img: `${imgLocation}/Shanks-Anime-Infobox.webp` },
    { name: "Blackbeard", power: 98, tag: "none", img: `${imgLocation}/Marshall-D-Teach-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Dragon", power: 97, tag: "none", img: `${imgLocation}/Monkey-D-Dragon-Anime-Infobox.webp` },
    { name: "Mihawk", power: 98, tag: "swordsman", img: `${imgLocation}/Dracule-Mihawk-Anime-Infobox.webp` },
    { name: "Akainu", power: 97, tag: "none", img: `${imgLocation}/Sakazuki-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Aokiji", power: 96, tag: "none", img: `${imgLocation}/Kuzan-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Kizaru", power: 96, tag: "none", img: `${imgLocation}/Borsalino-Anime-Infobox.webp` },
    { name: "Sengoku", power: 93, tag: "none", img: `${imgLocation}/Sengoku-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Fujitora", power: 93, tag: "swordsman", img: `${imgLocation}/Issho-Anime-Infobox.webp` },
    { name: "Eustass Kid", power: 87, tag: "none", img: `${imgLocation}/Eustass-Kid-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Law", power: 92, tag: "doctor", img: `${imgLocation}/Trafalgar-D-Water-Law-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Luffy", power: 98, tag: "none", img: `${imgLocation}/Monkey-D-Luffy-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Roronoa Zoro", power: 87, tag: "swordsman", img: `${imgLocation}/294-C69-BF-16-A8-4978-8701-43-EBDC0-C425-F.webp` },
    { name: "Sabo", power: 91, tag: "none", img: `${imgLocation}/Sabo-Anime-Infobox.webp` },
    { name: "Yamato", power: 87, tag: "none", img: `${imgLocation}/Yamato-Anime-Infobox.webp` },
    { name: "Ace", power: 86, tag: "none", img: `${imgLocation}/Portgas-D-Ace-Anime-Infobox.webp` },
    { name: "Marco", power: 88, tag: "healer", img: `${imgLocation}/Marco-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Ben Beckman", power: 87, tag: "sniper", img: `${imgLocation}/Benn-Beckman-Anime-Infobox.webp` },
    { name: "Rayleigh", power: 88, tag: "swordsman", img: `${imgLocation}/Silvers-Rayleigh-Anime-Infobox.webp` },
    { name: "Katakuri", power: 89, tag: "none", img: `${imgLocation}/Charlotte-Katakuri-Anime-Infobox.webp` },

    { name: "Boa Hancock", power: 84, tag: "none", img: `${imgLocation}/Boa-Hancock-Anime-Infobox.webp` },
    { name: "Doflamingo", power: 85, tag: "none", img: `${imgLocation}/Donquixote-Doflamingo-Anime-Infobox.webp` },
    { name: "Crocodile", power: 82, tag: "none", img: `${imgLocation}/Crocodile-Anime-Infobox.webp` },
    { name: "Jinbe", power: 88, tag: "fishman", img: `${imgLocation}/Jinbe-Anime-Infobox.webp` },
    { name: "Kuma", power: 88, tag: "cyborg", img: `${imgLocation}/Bartholomew-Kuma-Anime-Infobox.webp` },
    { name: "Gecko Moria", power: 80, tag: "shadow", img: `${imgLocation}/Gecko-Moria-Anime-Infobox.webp` },
    { name: "Magellan", power: 83, tag: "none", img: `${imgLocation}/Magellan-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Enel", power: 83, tag: "none", img: `${imgLocation}/Enel-Anime-Infobox.webp` },
    { name: "Urouge", power: 80, tag: "none", img: `${imgLocation}/Urouge-Anime-Infobox.webp` },
    { name: "Hawkins", power: 78, tag: "none", img: `${imgLocation}/Basil-Hawkins-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Apoo", power: 77, tag: "musician", img: `${imgLocation}/Scratchmen-Apoo-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Capone Bege", power: 77, tag: "none", img: `${imgLocation}/Capone-Bege-Anime-Post-Timeskip-Infobox.webp` },
    { name: "X Drake", power: 79, tag: "none", img: `${imgLocation}/X-Drake-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Killer", power: 78, tag: "swordsman", img: `${imgLocation}/Killer-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Jewelry Bonney", power: 75, tag: "none", img: `${imgLocation}/Jewelry-Bonney-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Cavendish", power: 77, tag: "swordsman", img: `${imgLocation}/Cavendish-Anime-Infobox.webp` },
    { name: "Bartolomeo", power: 79, tag: "none", img: `${imgLocation}/Bartolomeo-Anime-Infobox.webp` },
    { name: "Don Chinjao", power: 76, tag: "none", img: `${imgLocation}/Chinjao-Anime-Infobox.webp` },
    { name: "Sai", power: 74, tag: "none", img: `${imgLocation}/Sai-Anime-Infobox.webp` },
    { name: "Kyros", power: 76, tag: "swordsman", img: `${imgLocation}/Kyros-Anime-Infobox.webp` },
    { name: "Leo", power: 72, tag: "none", img: `${imgLocation}/Leo-Anime-Infobox.webp` },
    { name: "Rebecca", power: 71, tag: "swordsman", img: `${imgLocation}/Rebecca-Anime-Infobox.webp` },
    { name: "Tashigi", power: 70, tag: "swordsman", img: `${imgLocation}/Tashigi-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Smoker", power: 78, tag: "none", img: `${imgLocation}/Smoker-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Vergo", power: 77, tag: "none", img: `${imgLocation}/Vergo-With-Law-s-Heart.webp` },
    { name: "Rob Lucci", power: 85, tag: "none", img: `${imgLocation}/Rob-Lucci-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Kalifa", power: 74, tag: "assassin", img: `${imgLocation}/Kalifa-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Blueno", power: 72, tag: "none", img: `${imgLocation}/Blueno-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Fukurou", power: 70, tag: "none", img: `${imgLocation}/Fukurou-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Jabra", power: 72, tag: "none", img: `${imgLocation}/Jabra-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Kumadori", power: 71, tag: "none", img: `${imgLocation}/Kumadori-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Spandam", power: 3, tag: "none", img: `${imgLocation}/Spandam-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Perona", power: 71, tag: "shadow", img: `${imgLocation}/Perona-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Hody Jones", power: 74, tag: "fishman", img: `${imgLocation}/Hody-Jones-Anime-Infobox.webp` },
    { name: "Fisher Tiger", power: 82, tag: "fishman", img: `${imgLocation}/Fisher-Tiger-Anime-Infobox.webp` },
    { name: "Arlong", power: 65, tag: "fishman", img: `${imgLocation}/Arlong-Anime-Infobox.webp` },
    { name: "Sanji", power: 85, tag: "none", img: `${imgLocation}/Sanji-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Nami", power: 40, tag: "navigator", img: `${imgLocation}/Nami-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Usopp", power: 45, tag: "sniper", img: `${imgLocation}/Usopp-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Tony Tony Chopper", power: 45, tag: "doctor", img: `${imgLocation}/Tony-Tony-Chopper-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Franky", power: 68, tag: "cyborg", img: `${imgLocation}/Franky-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Brook", power: 67, tag: "musician", img: `${imgLocation}/Brook-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Nico Robin", power: 70, tag: "assassin", img: `${imgLocation}/Nico-robin-dressrosa-01.webp` },
    { name: "Coby", power: 79, tag: "none", img: `${imgLocation}/Koby-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Vivi", power: 35, tag: "navigator", img: `${imgLocation}/Nefertari-Vivi-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Carrot", power: 60, tag: "animal", img: `${imgLocation}/Carrot-Anime-Infobox.webp` },
    { name: "Pedro", power: 63, tag: "swordsman", img: `${imgLocation}/Pedro-Anime-Infobox.webp` },
    { name: "Wanda", power: 55, tag: "animal", img: `${imgLocation}/Wanda-Anime-Infobox.webp` },
    { name: "Bepo", power: 55, tag: "animal", img: `${imgLocation}/Bepo-Anime-Infobox.webp` },
    { name: "Kin’emon", power: 67, tag: "swordsman", img: `${imgLocation}/Kin-emon-Anime-Infobox.webp` },
    { name: "Kanjuro", power: 64, tag: "none", img: `${imgLocation}/Kanjuro-Anime-Infobox.webp` },

    { name: "Raizo", power: 63, tag: "assassin", img: `${imgLocation}/Raizo-Anime-Infobox.webp` },
    { name: "Shinobu", power: 58, tag: "assassin", img: `${imgLocation}/30de02f73df462ba4eab67d50fb3a441.webp` },
    { name: "Hyogoro", power: 35, tag: "none", img: `${imgLocation}/Hyougoro-Anime-Infobox.webp` },
    { name: "Denjiro", power: 69, tag: "swordsman", img: `${imgLocation}/Denjiro-Anime-Infobox.webp` },
    { name: "Kawamatsu", power: 67, tag: "fishman", img: `${imgLocation}/Kawamatsu-Anime-Infobox.webp` },
    { name: "Ashura Doji", power: 66, tag: "none", img: `${imgLocation}/Ashura-Doji-Anime-Infobox.webp` },
    { name: "Izo", power: 65, tag: "sniper", img: `${imgLocation}/Izo-Anime-Infobox.webp` },
    { name: "Crocus", power: 45, tag: "doctor", img: `${imgLocation}/Crocus-Age-47.webp` },
    { name: "Wapol", power: 50, tag: "none", img: `${imgLocation}/Wapol-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Dalton", power: 55, tag: "none", img: `${imgLocation}/Dalton-Anime-Infobox.webp` },
    { name: "Daz Bones", power: 65, tag: "swordsman", img: `${imgLocation}/Mr1.webp` },
    { name: "Bon Clay", power: 60, tag: "none", img: `${imgLocation}/Bentham-Anime-Infobox.webp` },
    { name: "Galdino", power: 58, tag: "none", img: `${imgLocation}/Galdino-Anime-Infobox.webp` },
    { name: "Miss Doublefinger", power: 56, tag: "assassin", img: `${imgLocation}/Zala-Anime-Infobox.webp` },
    { name: "Miss Merry Christmas", power: 44, tag: "animal", img: `${imgLocation}/Drophy-Anime-Infobox.webp` },
    { name: "Hina", power: 62, tag: "none", img: `${imgLocation}/Hina-Anime-Infobox.webp` },
    { name: "Bellamy", power: 60, tag: "none", img: `${imgLocation}/Bellamy-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Don Krieg", power: 50, tag: "none", img: `${imgLocation}/Krieg-Anime-Infobox.webp` },
    { name: "Gin", power: 52, tag: "none", img: `${imgLocation}/Gin-Anime-Infobox.webp` },
    { name: "Kuro", power: 48, tag: "swordsman", img: `${imgLocation}/Kuro-Anime-Infobox.webp` },
    { name: "Jango", power: 46, tag: "musician", img: `${imgLocation}/Jango-Anime-Infobox.webp` },
    { name: "Fullbody", power: 44, tag: "none", img: `${imgLocation}/Fullbody-Initial-Outfit.webp` },
    { name: "Alvida", power: 20, tag: "none", img: `${imgLocation}/Alvida-Anime-Infobox.webp` },
    { name: "Captain Morgan", power: 25, tag: "swordsman", img: `${imgLocation}/Morgan-Anime-Infobox.webp` },
    { name: "Pearl", power: 15, tag: "none", img: `${imgLocation}/Pearl-Anime-Infobox.webp` },
    { name: "Higuma", power: 10, tag: "none", img: `${imgLocation}/Higuma-Anime-Infobox.webp` },
    { name: "Mohji", power: 18, tag: "none", img: `${imgLocation}/Mohji-Anime-Infobox.webp` },
    { name: "Richie", power: 15, tag: "animal", img: `${imgLocation}/Richie-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Cabaji", power: 22, tag: "swordsman", img: `${imgLocation}/Cabaji-Anime-Infobox.webp` },
    { name: "Choo Choo", power: 20, tag: "fishman", img: `${imgLocation}/Chew-Anime-Infobox.webp` },
    { name: "Nezumi", power: 12, tag: "none", img: `${imgLocation}/Nezumi-Anime-Infobox.webp` },
    { name: "Satori", power: 30, tag: "none", img: `${imgLocation}/Satori-Anime-Infobox.webp` },
    { name: "Shura", power: 32, tag: "none", img: `${imgLocation}/Shura-Anime-Infobox.webp` },
    { name: "Ohm", power: 34, tag: "swordsman", img: `${imgLocation}/Ohm-Anime-Infobox.webp` },
    { name: "Gedatsu", power: 28, tag: "none", img: `${imgLocation}/Gedatsu-Anime-Infobox.webp` },
    { name: "Hotori", power: 22, tag: "none", img: `${imgLocation}/Hotori.webp` },
    { name: "Absalom", power: 35, tag: "assassin", img: `${imgLocation}/Absalom-Anime-Infobox.webp` },
    { name: "Hogback", power: 20, tag: "doctor", img: `${imgLocation}/Hogback-Anime-Infobox.webp` },
    { name: "Lola", power: 28, tag: "none", img: `${imgLocation}/Charlotte-Lola-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Dellinger", power: 35, tag: "none", img: `${imgLocation}/Dellinger.webp` },
    { name: "Lao G", power: 38, tag: "none", img: `${imgLocation}/Lao-G-Anime-Infobox.webp` },
    { name: "Baby 5", power: 30, tag: "none", img: `${imgLocation}/Baby-5-Anime-Infobox.webp` },
    { name: "Buffalo", power: 28, tag: "none", img: `${imgLocation}/Buffalo-Anime-Infobox.webp` },
    { name: "Senor Pink", power: 36, tag: "none", img: `${imgLocation}/Senor-Pink-Anime-Infobox.webp` },
    { name: "Gladius", power: 33, tag: "none", img: `${imgLocation}/Gladius-Anime-Infobox.webp` },
    { name: "Trebol", power: 38, tag: "none", img: `${imgLocation}/Trebol-Anime-Infobox.webp` },
    { name: "Diamante", power: 39, tag: "swordsman", img: `${imgLocation}/Diamante-Anime-Infobox.webp` },
    { name: "Pica", power: 39, tag: "giant", img: `${imgLocation}/Pica-One-Piece-600x600.webp` },
    { name: "Stelly", power: 12, tag: "none", img: `${imgLocation}/Sterry-at-Age-8.webp` },
    { name: "Neptune", power: 35, tag: "fishman", img: `${imgLocation}/Neptune-Anime-Infobox.webp` },
    { name: "Shirahoshi", power: 25, tag: "none", img: `${imgLocation}/Mermaid-Princess-Shirahoshi.webp` },
    { name: "Vander Decken", power: 33, tag: "none", img: `${imgLocation}/Vander-Decken-IX-Anime-Infobox.webp` },
    { name: "Hatchan", power: 32, tag: "fishman", img: `${imgLocation}/Hatchan-Anime-Infobox.webp` },
    { name: "Patti", power: 18, tag: "none", img: `${imgLocation}/Patty-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Kaya", power: 12, tag: "doctor", img: `${imgLocation}/3449c49f8282bbc2427e4e5f98a22bce.jpg` },
    { name: "Gaimon", power: 10, tag: "none", img: `${imgLocation}/Gaimon-Anime-Infobox.webp` },


    { name: "Kokoro", power: 15, tag: "none", img: `${imgLocation}/Kokoro-Anime-Infobox.webp` },
    { name: "Chimney", power: 10, tag: "none", img: `${imgLocation}/Chimney-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Gan Fall", power: 38, tag: "swordsman", img: `${imgLocation}/Gan-Fall-Robes.webp` },
    { name: "Konis", power: 15, tag: "navigator", img: `${imgLocation}/Conis-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Carue", power: 5, tag: "animal", img: `${imgLocation}/Karoo-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Kung-Fu Dugong", power: 7, tag: "animal", img: `${imgLocation}/7xy7x7ela1561.png` },
    { name: "Chouchou", power: 4, tag: "animal", img: `${imgLocation}/Chouchou.webp` },
    { name: "Laboon", power: 9, tag: "animal", img: `${imgLocation}/Little-Laboon.webp` },
    { name: "Surume", power: 9, tag: "animal", img: `${imgLocation}/images.webp` },
    { name: "Pappug", power: 4, tag: "none", img: `${imgLocation}/Pappag-Anime-Post-Timeskip-Infobox.webp` },
    { name: "Duval", power: 6, tag: "none", img: `${imgLocation}/755be6a5e4180c4ab00783155cd49b45.webp` },
    { name: "Wanze", power: 7, tag: "none", img: `${imgLocation}/Wanze-Anime-Infobox.webp` },
    { name: "Foxxy", power: 6, tag: "none", img: `${imgLocation}/Foxy-Anime-Pre-Timeskip-Infobox.webp` },
    { name: "Tonjit", power: 2, tag: "none", img: `${imgLocation}/Tonjit-Anime-Infobox.webp` },
    { name: "Yosaku", power: 8, tag: "swordsman", img: `${imgLocation}/actor-yosaku-one-piece-534463-large.jpg` },
    { name: "Johnny", power: 8, tag: "swordsman", img: `${imgLocation}/Johnny-giovane.webp` },
    { name: "Shoujou", power: 7, tag: "none", img: `${imgLocation}/Shoujou-Anime-Infobox.webp` },
    { name: "Random Marine", power: 5, tag: "none", img: `${imgLocation}/Ukkari-Anime-Infobox.webp` },
    { name: "Makino", power: 4, tag: "none", img: `${imgLocation}/Makino-Ace-Ask-Manners.webp` },
];

export default characters






