const characters = [
    { name: "Gol D. Roger", power: 100, tag: "none", img: "https://i.ibb.co/JwF3tCnF/Gol-D-Roger.webp" },
    { name: "Whitebeard", power: 100, tag: "none", img: "https://i.ibb.co/VY9r9wnB/Edward-Newgate-Anime-Infobox.webp" },
    { name: "Kaido", power: 98, tag: "giant", img: "https://i.ibb.co/G3Jvq74K/Kaidou-Anime-Infobox.webp" },
    { name: "Big Mom", power: 97, tag: "giant", img: "https://i.ibb.co/yBQv7gKk/Charlotte-Linlin-Anime-Infobox.webp" },
    { name: "Shanks", power: 98, tag: "swordsman", img: "https://i.ibb.co/jPgXKPYy/Shanks-Anime-Infobox.webp" },
    { name: "Blackbeard", power: 98, tag: "none", img: "https://i.ibb.co/Xft1S3C2/Marshall-D-Teach-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Dragon", power: 97, tag: "none", img: "https://i.ibb.co/ZR3vmfkJ/Monkey-D-Dragon-Anime-Infobox.webp" },
    { name: "Mihawk", power: 98, tag: "swordsman", img: "https://i.ibb.co/8LQkcYds/Dracule-Mihawk-Anime-Infobox.webp" },
    { name: "Akainu", power: 97, tag: "none", img: "https://i.ibb.co/B5fGcTJh/Sakazuki-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Aokiji", power: 96, tag: "none", img: "https://i.ibb.co/bjK3C1kL/Kuzan-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Kizaru", power: 96, tag: "none", img: "https://i.ibb.co/JWppLPds/Borsalino-Anime-Infobox.webp" },
    { name: "Sengoku", power: 93, tag: "none", img: "https://i.ibb.co/DXtL6sz/Sengoku-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Monkey D. Garp", power: 95, tag: "none", img: "https://i.ibb.co/hFGXTgpY/Monkey-D-Garp-Anime-Infobox.webp" },
    { name: "Fujitora", power: 93, tag: "swordsman", img: "https://i.ibb.co/DfJKdzWy/Issho-Anime-Infobox.webp" },
    { name: "Eustass Kid", power: 90, tag: "none", img: "https://i.ibb.co/7NYbMnRz/Eustass-Kid-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Law", power: 92, tag: "doctor", img: "https://i.ibb.co/5gWh13H0/Trafalgar-D-Water-Law-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Luffy", power: 95, tag: "none", img: "https://i.ibb.co/b5TR59pN/Monkey-D-Luffy-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Roronoa Zoro", power: 90, tag: "swordsman", img: "https://i.ibb.co/s9sQRGrf/294-C69-BF-16-A8-4978-8701-43-EBDC0-C425-F.webp" },
    { name: "Sabo", power: 91, tag: "none", img: "https://i.ibb.co/QvWfGT5j/Sabo-Anime-Infobox.webp" },
    { name: "Yamato", power: 90, tag: "none", img: "https://i.ibb.co/0pQfGm60/Yamato-Anime-Infobox.webp" },
    { name: "Ace", power: 89, tag: "none", img: "https://i.ibb.co/QvrRcrpK/Portgas-D-Ace-Anime-Infobox.webp" },
    { name: "Marco", power: 88, tag: "healer", img: "https://i.ibb.co/CpnP0QkG/Marco-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Ben Beckman", power: 87, tag: "sniper", img: "https://i.ibb.co/1tN4S9yh/Benn-Beckman-Anime-Infobox.webp" },
    { name: "Rayleigh", power: 88, tag: "swordsman", img: "https://i.ibb.co/XZzVXpd2/Silvers-Rayleigh-Anime-Infobox.webp" },
    { name: "Katakuri", power: 89, tag: "none", img: "https://i.ibb.co/27Rxrc2M/Charlotte-Katakuri-Anime-Infobox.webp" },
    { name: "Boa Hancock", power: 84, tag: "none", img: "https://i.ibb.co/yBcF15b2/Boa-Hancock-Anime-Infobox.webp" },
    { name: "Doflamingo", power: 85, tag: "none", img: "https://i.ibb.co/gLfy7myr/Donquixote-Doflamingo-Anime-Infobox.webp" },
    { name: "Crocodile", power: 82, tag: "none", img: "https://i.ibb.co/MD2Q3L8m/Crocodile-Anime-Infobox.webp" },
    { name: "Jinbe", power: 88, tag: "fishman", img: "https://i.ibb.co/QjHHsYBF/Jinbe-Anime-Infobox.webp" },
    { name: "Kuma", power: 86, tag: "cyborg", img: "https://i.ibb.co/S7QXmWc9/Bartholomew-Kuma-Anime-Infobox.webp" },
    { name: "Gecko Moria", power: 80, tag: "shadow", img: "https://i.ibb.co/TBkZxk07/Gecko-Moria-Anime-Infobox.webp" },
    { name: "Magellan", power: 83, tag: "none", img: "https://i.ibb.co/MkgzPwwT/Magellan-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Enel", power: 83, tag: "none", img: "https://i.ibb.co/rKkkhSy1/Enel-Anime-Infobox.webp" },
    { name: "Urouge", power: 80, tag: "none", img: "https://i.ibb.co/JFMBTyvV/Urouge-Anime-Infobox.webp" },
    { name: "Hawkins", power: 78, tag: "none", img: "https://i.ibb.co/gb8t3KRM/Basil-Hawkins-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Apoo", power: 77, tag: "musician", img: "https://i.ibb.co/v4FdNYTY/Scratchmen-Apoo-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Capone Bege", power: 77, tag: "none", img: "https://i.ibb.co/nNLMh5fT/Capone-Bege-Anime-Post-Timeskip-Infobox.webp" },
    { name: "X Drake", power: 79, tag: "none", img: "https://i.ibb.co/7JdJqKT1/X-Drake-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Killer", power: 78, tag: "swordsman", img: "https://i.ibb.co/FqwR3LP3/Killer-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Jewelry Bonney", power: 75, tag: "none", img: "https://i.ibb.co/b5N81bv3/Jewelry-Bonney-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Cavendish", power: 77, tag: "swordsman", img: "https://i.ibb.co/XfRVBLQN/Cavendish-Anime-Infobox.webp" },
    { name: "Bartolomeo", power: 76, tag: "none", img: "https://i.ibb.co/Kc1MxQ3r/Bartolomeo-Anime-Infobox.webp" },
    { name: "Don Chinjao", power: 76, tag: "none", img: "https://i.ibb.co/r2NRs0Nz/Chinjao-Anime-Infobox.webp" },
    { name: "Sai", power: 74, tag: "none", img: "https://i.ibb.co/LXn7jmJZ/Sai-Anime-Infobox.webp" },
    { name: "Kyros", power: 76, tag: "swordsman", img: "https://i.ibb.co/fVqT8D9K/Kyros-Anime-Infobox.webp" },
    { name: "Leo", power: 72, tag: "none", img: "https://i.ibb.co/Wv3JT9Xn/Leo-Anime-Infobox.webp" },
    { name: "Rebecca", power: 71, tag: "swordsman", img: "https://i.ibb.co/PzcNKzgm/Rebecca-Anime-Infobox.webp" },
    { name: "Tashigi", power: 70, tag: "swordsman", img: "https://i.ibb.co/1J6MJrS7/Tashigi-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Smoker", power: 78, tag: "none", img: "https://i.ibb.co/dwRzmLLy/Smoker-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Vergo", power: 77, tag: "none", img: "https://i.ibb.co/qYWndwCZ/Vergo-With-Law-s-Heart.webp" },
    { name: "Rob Lucci", power: 85, tag: "none", img: "https://i.ibb.co/6c8nw5kf/Rob-Lucci-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Kalifa", power: 74, tag: "assassin", img: "https://i.ibb.co/n8jqLv7L/Kalifa-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Blueno", power: 72, tag: "none", img: "https://i.ibb.co/8gCVRhQx/Blueno-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Fukurou", power: 70, tag: "none", img: "https://i.ibb.co/kgZqFZ7s/Fukurou-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Jabra", power: 72, tag: "none", img: "https://i.ibb.co/gXGVqVj/Jabra-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Kumadori", power: 71, tag: "none", img: "https://i.ibb.co/nNgZnssS/Kumadori-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Spandam", power: 3, tag: "none", img: "https://i.ibb.co/9FS9Rqg/Spandam-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Perona", power: 71, tag: "shadow", img: "https://i.ibb.co/JF21dWwx/Perona-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Hody Jones", power: 74, tag: "fishman", img: "https://i.ibb.co/yBMHhMsQ/Hody-Jones-Anime-Infobox.webp" },
    { name: "Fisher Tiger", power: 85, tag: "fishman", img: "https://i.ibb.co/PZ9z3FkK/Fisher-Tiger-Anime-Infobox.webp" },
    { name: "Arlong", power: 72, tag: "fishman", img: "https://i.ibb.co/QjpGncwb/Arlong-Anime-Infobox.webp" },
    { name: "Sanji", power: 85, tag: "none", img: "https://i.ibb.co/RkkS0nyX/Sanji-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Nami", power: 40, tag: "navigator", img: "https://i.ibb.co/M5D9gDFw/Nami-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Usopp", power: 45, tag: "sniper", img: "https://i.ibb.co/tRShzjB/Usopp-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Tony Tony Chopper", power: 45, tag: "doctor", img: "https://i.ibb.co/kV07mqsZ/Tony-Tony-Chopper-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Franky", power: 68, tag: "cyborg", img: "https://i.ibb.co/5XP45Ph4/Franky-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Brook", power: 67, tag: "musician", img: "https://i.ibb.co/0yWZrQDC/Brook-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Nico Robin", power: 70, tag: "assassin", img: "https://i.ibb.co/ch6wsXMw/Nico-robin-dressrosa-01.webp" },
    { name: "Coby", power: 65, tag: "none", img: "https://i.ibb.co/0VYRZH7m/Koby-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Vivi", power: 35, tag: "navigator", img: "https://i.ibb.co/yFLWbgdD/Nefertari-Vivi-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Carrot", power: 60, tag: "animal", img: "https://i.ibb.co/ym0c8vvh/Carrot-Anime-Infobox.webp" },
    { name: "Pedro", power: 63, tag: "swordsman", img: "https://i.ibb.co/r2snrc8W/Pedro-Anime-Infobox.webp" },
    { name: "Wanda", power: 55, tag: "animal", img: "https://i.ibb.co/1JsFMSJN/Wanda-Anime-Infobox.webp" },
    { name: "Bepo", power: 55, tag: "animal", img: "https://i.ibb.co/7dz08dHP/Bepo-Anime-Infobox.webp" },
    { name: "Kin’emon", power: 67, tag: "swordsman", img: "https://i.ibb.co/BKTCBWvS/Kin-emon-Anime-Infobox.webp" },
    { name: "Kanjuro", power: 64, tag: "none", img: "https://i.ibb.co/VWNYHJR9/Kanjuro-Anime-Infobox.webp" },
    { name: "Raizo", power: 63, tag: "assassin", img: "https://i.ibb.co/1ftVfBqP/Raizo-Anime-Infobox.webp" },
    { name: "Shinobu", power: 58, tag: "assassin", img: "https://i.ibb.co/nM7h3xzJ/30de02f73df462ba4eab67d50fb3a441.webp" },
    { name: "Hyogoro", power: 35, tag: "none", img: "https://i.ibb.co/XZDMCB8p/Hyougoro-Anime-Infobox.webp" },
    { name: "Denjiro", power: 69, tag: "swordsman", img: "https://i.ibb.co/Zpy8nJJm/Denjiro-Anime-Infobox.webp" },
    { name: "Kawamatsu", power: 67, tag: "fishman", img: "https://i.ibb.co/7dK1WbHk/Kawamatsu-Anime-Infobox.webp" },
    { name: "Ashura Doji", power: 66, tag: "none", img: "https://i.ibb.co/rR0zDhQL/Ashura-Doji-Anime-Infobox.webp" },
    { name: "Izo", power: 65, tag: "sniper", img: "https://i.ibb.co/1fDY4R7c/Izo-Anime-Infobox.webp" },
    { name: "Crocus", power: 45, tag: "doctor", img: "https://i.ibb.co/v4f7StLr/Crocus-Age-47.webp" },
    { name: "Wapol", power: 50, tag: "none", img: "https://i.ibb.co/gbrfw30s/Wapol-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Dalton", power: 55, tag: "none", img: "https://i.ibb.co/xStjs307/Dalton-Anime-Infobox.webp" },
    { name: "Daz Bones", power: 65, tag: "swordsman", img: "https://i.ibb.co/DTNRz08/Mr1.webp" },
    { name: "Bon Clay", power: 60, tag: "none", img: "https://i.ibb.co/TqBLQmRQ/Bentham-Anime-Infobox.webp" },
    { name: "Galdino", power: 58, tag: "none", img: "https://i.ibb.co/kVm7Q6ps/Galdino-Anime-Infobox.webp" },
    { name: "Miss Doublefinger", power: 56, tag: "assassin", img: "https://i.ibb.co/Mx3y9LnS/Zala-Anime-Infobox.webp" },
    { name: "Miss Merry Christmas", power: 44, tag: "animal", img: "https://i.ibb.co/ZpLtGGR4/Drophy-Anime-Infobox.webp" },
    { name: "Hina", power: 62, tag: "none", img: "https://i.ibb.co/C5mCx1FH/Hina-Anime-Infobox.webp" },
    { name: "Bellamy", power: 60, tag: "none", img: "https://i.ibb.co/MDHgxLJS/Bellamy-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Don Krieg", power: 50, tag: "none", img: "https://i.ibb.co/mry7DbrG/Krieg-Anime-Infobox.webp" },
    { name: "Gin", power: 52, tag: "none", img: "https://i.ibb.co/j94gYgn1/Gin-Anime-Infobox.webp" },
    { name: "Kuro", power: 48, tag: "swordsman", img: "https://i.ibb.co/ymJ8RM0H/Kuro-Anime-Infobox.webp" },
    { name: "Jango", power: 46, tag: "musician", img: "https://i.ibb.co/3mdTGW9m/Jango-Anime-Infobox.webp" },
    { name: "Fullbody", power: 44, tag: "none", img: "https://i.ibb.co/N6XG6dNF/Fullbody-Initial-Outfit.webp" },
    { name: "Alvida", power: 20, tag: "none", img: "https://i.ibb.co/Z5dp3vD/Alvida-Anime-Infobox.webp" },
    { name: "Captain Morgan", power: 25, tag: "swordsman", img: "https://i.ibb.co/pjMfLdzC/Morgan-Anime-Infobox.webp" },
    { name: "Pearl", power: 15, tag: "none", img: "https://i.ibb.co/WNxv0KQG/Pearl-Anime-Infobox.webp" },
    { name: "Higuma", power: 10, tag: "none", img: "https://i.ibb.co/4nb5s915/Higuma-Anime-Infobox.webp" },
    { name: "Mohji", power: 18, tag: "none", img: "https://i.ibb.co/DPL2mgt0/Mohji-Anime-Infobox.webp" },
    { name: "Richie", power: 15, tag: "animal", img: "https://i.ibb.co/RpfztxcH/Richie-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Cabaji", power: 22, tag: "swordsman", img: "https://i.ibb.co/67ZW8TWS/Cabaji-Anime-Infobox.webp" },
    { name: "Choo Choo", power: 20, tag: "fishman", img: "https://i.ibb.co/d0CnYqzP/Chew-Anime-Infobox.webp" },
    { name: "Nezumi", power: 12, tag: "none", img: "https://i.ibb.co/3m5rncV5/Nezumi-Anime-Infobox.webp" },
    { name: "Satori", power: 30, tag: "none", img: "https://i.ibb.co/WW1chYzN/Satori-Anime-Infobox.webp" },
    { name: "Shura", power: 32, tag: "none", img: "https://i.ibb.co/Fb1G64B2/Shura-Anime-Infobox.webp" },
    { name: "Ohm", power: 34, tag: "swordsman", img: "https://i.ibb.co/RkQ3pjB5/Ohm-Anime-Infobox.webp" },
    { name: "Gedatsu", power: 28, tag: "none", img: "https://i.ibb.co/fGQKVchh/Gedatsu-Anime-Infobox.webp" },
    { name: "Hotori", power: 22, tag: "none", img: "https://i.ibb.co/N25xzyBy/Hotori.webp" },
    { name: "Absalom", power: 35, tag: "assassin", img: "https://i.ibb.co/WWCszrBk/Absalom-Anime-Infobox.webp" },
    { name: "Hogback", power: 20, tag: "doctor", img: "https://i.ibb.co/93tg2X77/Hogback-Anime-Infobox.webp" },
    { name: "Lola", power: 28, tag: "none", img: "https://i.ibb.co/gLnL7Yff/Charlotte-Lola-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Dellinger", power: 35, tag: "none", img: "https://i.ibb.co/cSqLK4jX/Dellinger.webp" },
    { name: "Lao G", power: 38, tag: "none", img: "https://i.ibb.co/Wv1skfg5/Lao-G-Anime-Infobox.webp" },
    { name: "Baby 5", power: 30, tag: "none", img: "https://i.ibb.co/mrRzSHFY/Baby-5-Anime-Infobox.webp" },
    { name: "Buffalo", power: 28, tag: "none", img: "https://i.ibb.co/1YSm1kc2/Buffalo-Anime-Infobox.webp" },
    { name: "Senor Pink", power: 36, tag: "none", img: "https://i.ibb.co/6cT5y9kp/Senor-Pink-Anime-Infobox.webp" },
    { name: "Gladius", power: 33, tag: "none", img: "https://i.ibb.co/bM4pP1QN/Gladius-Anime-Infobox.webp" },
    { name: "Trebol", power: 38, tag: "none", img: "https://i.ibb.co/nMpRyGdC/Trebol-Anime-Infobox.webp" },
    { name: "Diamante", power: 39, tag: "swordsman", img: "https://i.ibb.co/svYJ6fT8/Diamante-Anime-Infobox.webp" },
    { name: "Pica", power: 39, tag: "giant", img: "https://i.ibb.co/Gvctztdf/Pica-One-Piece-600x600.webp" },
    { name: "Stelly", power: 12, tag: "none", img: "https://i.ibb.co/0yQdcH22/Sterry-at-Age-8.webp" },
    { name: "Neptune", power: 35, tag: "fishman", img: "https://i.ibb.co/vvwg50h1/Neptune-Anime-Infobox.webp" },
    { name: "Shirahoshi", power: 25, tag: "none", img: "https://i.ibb.co/ZRrq71LV/Mermaid-Princess-Shirahoshi.webp" },
    { name: "Vander Decken", power: 33, tag: "none", img: "https://i.ibb.co/gZ0KzM0y/Vander-Decken-IX-Anime-Infobox.webp" },
    { name: "Hatchan", power: 32, tag: "fishman", img: "https://i.ibb.co/XQk2Bp4/Hatchan-Anime-Infobox.webp" },
    { name: "Patti", power: 18, tag: "none", img: "https://i.ibb.co/KzsmC6yx/Patty-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Kaya", power: 12, tag: "doctor", img: "https://i.ibb.co/bRW3btPf/3449c49f8282bbc2427e4e5f98a22bce.jpg" },
    { name: "Gaimon", power: 10, tag: "none", img: "https://i.ibb.co/230h3bD9/Gaimon-Anime-Infobox.webp" },
    { name: "Kokoro", power: 15, tag: "none", img: "https://i.ibb.co/tw3Fstpp/Kokoro-Anime-Infobox.webp" },
    { name: "Chimney", power: 10, tag: "none", img: "https://i.ibb.co/m5WZzPdd/Chimney-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Gan Fall", power: 38, tag: "swordsman", img: "https://i.ibb.co/R401mLYK/Gan-Fall-Robes.webp" },
    { name: "Konis", power: 15, tag: "navigator", img: "https://i.ibb.co/0pc5nrhL/Conis-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Carue", power: 5, tag: "animal", img: "https://i.ibb.co/sJjbZT0K/Karoo-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Kung-Fu Dugong", power: 7, tag: "animal", img: "https://i.ibb.co/4gZg1tjc/7xy7x7ela1561.png" },
    { name: "Chouchou", power: 4, tag: "animal", img: "https://i.ibb.co/gFf4720c/Chouchou.webp" },
    { name: "Laboon", power: 9, tag: "animal", img: "https://i.ibb.co/j993K78T/Little-Laboon.webp" },
    { name: "Surume", power: 9, tag: "animal", img: "https://i.ibb.co/7xVLKxDw/images.webp" },
    { name: "Pappug", power: 4, tag: "none", img: "https://i.ibb.co/20NwV44j/Pappag-Anime-Post-Timeskip-Infobox.webp" },
    { name: "Duval", power: 6, tag: "none", img: "https://i.ibb.co/5WDgm4N2/755be6a5e4180c4ab00783155cd49b45.webp" },
    { name: "Wanze", power: 7, tag: "none", img: "https://i.ibb.co/wZmtSgHC/Wanze-Anime-Infobox.webp" },
    { name: "Foxxy", power: 6, tag: "none", img: "https://i.ibb.co/fdRwM6Fw/Foxy-Anime-Pre-Timeskip-Infobox.webp" },
    { name: "Tonjit", power: 2, tag: "none", img: "https://i.ibb.co/gFDMHRX1/Tonjit-Anime-Infobox.webp" },
    { name: "Yosaku", power: 8, tag: "swordsman", img: "https://i.ibb.co/cSH2kHQQ/actor-yosaku-one-piece-534463-large.jpg" },
    { name: "Johnny", power: 8, tag: "swordsman", img: "https://i.ibb.co/XxxLx8C0/Johnny-giovane.webp" },
    { name: "Shoujou", power: 7, tag: "none", img: "https://i.ibb.co/rRX178y5/Shoujou-Anime-Infobox.webp" },
    { name: "Random Marine", power: 5, tag: "none", img: "https://i.ibb.co/Z1Vv4RJZ/Ukkari-Anime-Infobox.webp" },
    { name: "Makino", power: 4, tag: "none", img: "https://i.ibb.co/LDnBHynm/Makino-Ace-Ask-Manners.webp" },
];

export default characters






